server:
  port: 8080 # Standard port for REST API

spring:
  # Database settings (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/gym_db
    username: anastasiia
    password:
    driver-class-name: org.postgresql.Driver
  sql:
    init.mode: always
  application:
    name: gym-main-service # Чтобы в Eureka он был виден под нормальным именем
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    template:
      default-destination: trainer-workload-queue

  # JPA/Hibernate settings
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # DB schema management (update, create, validate)
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  # AOP settings
  aop:
    proxy-target-class: true

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose all endpoints (health, info, metrics, prometheus, etc.)
  endpoint:
    health:
      show-details: always # Show details for health checks

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 day token's live

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      workloadService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50